version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .gitignore/.env 
    environment:
      NODE_ENV: development
      NEW_RELIC_NO_CONFIG_FILE: "true"
      NEW_RELIC_APP_NAME: "devops-monitoreo"
      NEW_RELIC_LOG_LEVEL: "info"
    volumes:
      - .:/app
    command: npm start
