name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Clonaa el repositorio

    - name: Build Docker image
      run: docker build -t diegom648/devops .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push diegom648/devops
    

  deploy-to-render:
        needs: build-and-deploy
        runs-on: ubuntu-latest
        steps:
          - name: Deploy to Render
            uses: render-oss/deploy-action@v1
            with:
              apiKey: ${{ secrets.RENDER_API_KEY }}
              serviceId: <srv-csf5219u0jms73fdb420>
              clearCache: true
    
