name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install Dependencies
        run: npm ci  

      - name: Run Tests
        run: npm test 

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Build Docker image
        run: docker-compose build  
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker-compose push  

  deploy-to-render:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          echo "Deploying to Render..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "'"${{ secrets.SERVICE_ID }}"'",
              "clearCache": true
            }' \
            https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deploys
